#!/usr/bin/env bash
# render-traefik-tls.sh — turn the two Traefik templates into the running config.
#
# setup.sh calls this; it is a separate script so the TLS decision is testable
# on its own, without a stack, a certificate, or an ACME account. Both modes come
# out of ONE template pair (see traefik/traefik.yml.tpl for why).
#
# Inputs (environment):
#   TETRIX_TLS_MODE      self_signed (default) | acme
#   TETRIX_HOST          the public hostname
#   TETRIX_TRAEFIK_DIR   output root (default: the bundle's own traefik/)
#   TETRIX_ACME_EMAIL    ACME registration address
#   TETRIX_ACME_CA_SERVER  ACME directory (default: Let's Encrypt production)
#   TETRIX_DEPLOYMENT_MODE dev (default) | cloud
#
# ACME is accepted ONLY in cloud mode and ONLY for a *.tetrix.deskree.com host.
# That is not a style rule: Let's Encrypt HTTP-01 needs a publicly resolvable
# name, and an ACME order for tetrix.local burns rate limit against a name that
# can never validate — while leaving the developer with no certificate at all.
set -euo pipefail

BUNDLE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

MODE="${TETRIX_TLS_MODE:-self_signed}"
DEPLOY_MODE="${TETRIX_DEPLOYMENT_MODE:-dev}"
HOST="${TETRIX_HOST:-tetrix.local}"
OUT_DIR="${TETRIX_TRAEFIK_DIR:-${BUNDLE}/traefik}"
ACME_EMAIL="${TETRIX_ACME_EMAIL:-platform@deskree.com}"
ACME_CA="${TETRIX_ACME_CA_SERVER:-https://acme-v02.api.letsencrypt.org/directory}"
PLATFORM_DOMAIN="${TETRIX_PLATFORM_DOMAIN:-tetrix.deskree.com}"

STATIC_TPL="${BUNDLE}/traefik/traefik.yml.tpl"
TLS_TPL="${BUNDLE}/traefik/dynamic/tls.yml.tpl"

for f in "$STATIC_TPL" "$TLS_TPL"; do
  [ -f "$f" ] || { echo "ERROR: template is absent: ${f}" >&2; exit 2; }
done

case "$MODE" in
  self_signed) ;;
  acme)
    # A platform hostname, and nothing else.
    if ! printf '%s' "$HOST" | grep -Eq "^[a-z][a-z0-9-]*[a-z0-9]\.${PLATFORM_DOMAIN//./\\.}$"; then
      echo "ERROR: TETRIX_TLS_MODE=acme requires a ${PLATFORM_DOMAIN} hostname (got ${HOST})" >&2
      exit 2
    fi
    [ -n "$ACME_EMAIL" ] || { echo "ERROR: TETRIX_ACME_EMAIL is required for acme mode" >&2; exit 2; }
    ;;
  *)
    echo "ERROR: TETRIX_TLS_MODE must be self_signed or acme (got ${MODE})" >&2
    exit 2
    ;;
esac

# Cloud is the only place ACME belongs; a dev box that reached here with
# acme has almost certainly inherited a stale cloud.env.
if [ "$MODE" = "acme" ] && [ "$DEPLOY_MODE" != "cloud" ]; then
  echo "ERROR: TETRIX_TLS_MODE=acme is only accepted in cloud mode" >&2
  exit 2
fi

install -d -m 0755 "${OUT_DIR}/dynamic"

MODE="$MODE" ACME_EMAIL="$ACME_EMAIL" ACME_CA="$ACME_CA" \
STATIC_TPL="$STATIC_TPL" TLS_TPL="$TLS_TPL" OUT_DIR="$OUT_DIR" \
python3 <<'PY'
import os
import pathlib

mode = os.environ["MODE"]
out = pathlib.Path(os.environ["OUT_DIR"])

if mode == "acme":
    websecure_tls = "\n".join([
        "    http:",
        "      tls:",
        "        certResolver: letsencrypt",
    ])
    acme_resolver = "\n".join([
        "",
        "certificatesResolvers:",
        "  letsencrypt:",
        "    acme:",
        f'      email: {os.environ["ACME_EMAIL"]}',
        "      storage: /acme/acme.json",
        f'      caServer: {os.environ["ACME_CA"]}',
        "      httpChallenge:",
        "        entryPoint: web",
    ])
    tls_block = "\n".join([
        "# ACME mode: the letsencrypt resolver owns the certificate. No certFile.",
        "tls:",
        "  options:",
        "    default:",
        "      minVersion: VersionTLS12",
    ])
else:
    websecure_tls = None
    acme_resolver = None
    tls_block = "\n".join([
        "tls:",
        "  certificates:",
        "    - certFile: /certs/cert.pem",
        "      keyFile: /certs/key.pem",
        "  stores:",
        "    default:",
        "      defaultCertificate:",
        "        certFile: /certs/cert.pem",
        "        keyFile: /certs/key.pem",
    ])


def render(template: pathlib.Path, markers: dict) -> str:
    lines = []
    for line in template.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped in markers:
            value = markers[stripped]
            if value is not None:
                lines.append(value)
            continue
        lines.append(line)
    return "\n".join(lines) + "\n"


header = ("# GENERATED by scripts/render-traefik-tls.sh — do not edit.\n"
          f"# TLS mode: {mode}\n")

static = render(pathlib.Path(os.environ["STATIC_TPL"]), {
    "#@WEBSECURE_TLS@": websecure_tls,
    "#@ACME_RESOLVER@": acme_resolver,
})
dynamic = render(pathlib.Path(os.environ["TLS_TPL"]), {
    "#@TLS_BLOCK@": tls_block,
})

(out / "traefik.yml").write_text(header + static, encoding="utf-8")
(out / "dynamic" / "tls.yml").write_text(header + dynamic, encoding="utf-8")
PY

echo "Rendered Traefik ${MODE} config into ${OUT_DIR}"
